import type { ViewerSessionStore } from "@/stores/viewer-session/types";

export const viewerSessionSelectors = {
  uiState: (state: ViewerSessionStore) => ({
    viewerSettings: state.viewerSettings,
    activeViewportTool: state.activeViewportTool,
    viewportLayoutId: state.viewportLayoutId,
    maximizedViewportId: state.maximizedViewportId,
    selectedViewportId: state.selectedViewportId,
    annotationListOpen: state.annotationListOpen,
    keyImageListOpen: state.keyImageListOpen,
    dicomTagDialogViewportId: state.dicomTagDialogViewportId,
    settingsOpen: state.settingsOpen,
  }),
  viewportState: (state: ViewerSessionStore) => ({
    viewportSeriesAssignments: state.viewportSeriesAssignments,
    viewportInvertEnabled: state.viewportInvertEnabled,
    viewportToolGroupSelections: state.viewportToolGroupSelections,
    annotationCommand: state.annotationCommand,
    viewCommand: state.viewCommand,
    viewportAnnotationsStateById: state.viewportAnnotationsStateById,
    viewportImageLayoutIdById: state.viewportImageLayoutIdById,
    viewportModeById: state.viewportModeById,
    viewportMprLayoutIdById: state.viewportMprLayoutIdById,
    viewportMprSlabStateById: state.viewportMprSlabStateById,
    viewportCellSelectionById: state.viewportCellSelectionById,
    viewportCineStateById: state.viewportCineStateById,
    viewportKeyImagesBySeriesKey: state.viewportKeyImagesBySeriesKey,
    stackViewportRuntimeStateById: state.stackViewportRuntimeStateById,
    viewportStackNavigationCommandById: state.viewportStackNavigationCommandById,
  }),
  syncState: (state: ViewerSessionStore) => ({
    referenceLinesEnabled: state.referenceLinesEnabled,
    viewportSequenceSyncStateById: state.viewportSequenceSyncStateById,
    stackViewportReferenceLineStateById: state.stackViewportReferenceLineStateById,
    mprViewportReferenceLineStateById: state.mprViewportReferenceLineStateById,
    stackViewportPresentationStateById: state.stackViewportPresentationStateById,
    viewportSequenceSyncCommandById: state.viewportSequenceSyncCommandById,
    viewportPresentationSyncCommandById: state.viewportPresentationSyncCommandById,
    viewportMprCrosshairSyncCommandById: state.viewportMprCrosshairSyncCommandById,
    crossStudyCalibrationByPairKey: state.crossStudyCalibrationByPairKey,
    manualSequenceSyncRequest: state.manualSequenceSyncRequest,
  }),
  actions: (state: ViewerSessionStore) => ({
    setViewerSettings: state.setViewerSettings,
    setActiveViewportTool: state.setActiveViewportTool,
    setViewportLayoutId: state.setViewportLayoutId,
    setMaximizedViewportId: state.setMaximizedViewportId,
    setSelectedViewportId: state.setSelectedViewportId,
    setReferenceLinesEnabled: state.setReferenceLinesEnabled,
    setViewportSeriesAssignments: state.setViewportSeriesAssignments,
    setViewportInvertEnabled: state.setViewportInvertEnabled,
    setViewportToolGroupSelections: state.setViewportToolGroupSelections,
    setAnnotationCommand: state.setAnnotationCommand,
    setViewCommand: state.setViewCommand,
    setViewportAnnotationsStateById: state.setViewportAnnotationsStateById,
    setViewportImageLayoutIdById: state.setViewportImageLayoutIdById,
    setViewportModeById: state.setViewportModeById,
    setViewportMprLayoutIdById: state.setViewportMprLayoutIdById,
    setViewportMprSlabStateById: state.setViewportMprSlabStateById,
    setViewportCellSelectionById: state.setViewportCellSelectionById,
    setViewportCineStateById: state.setViewportCineStateById,
    setViewportKeyImagesBySeriesKey: state.setViewportKeyImagesBySeriesKey,
    setViewportSequenceSyncStateById: state.setViewportSequenceSyncStateById,
    setStackViewportRuntimeStateById: state.setStackViewportRuntimeStateById,
    setStackViewportReferenceLineStateById:
      state.setStackViewportReferenceLineStateById,
    setMprViewportReferenceLineStateById:
      state.setMprViewportReferenceLineStateById,
    setStackViewportPresentationStateById:
      state.setStackViewportPresentationStateById,
    setViewportStackNavigationCommandById:
      state.setViewportStackNavigationCommandById,
    setViewportSequenceSyncCommandById:
      state.setViewportSequenceSyncCommandById,
    setViewportPresentationSyncCommandById:
      state.setViewportPresentationSyncCommandById,
    setViewportMprCrosshairSyncCommandById:
      state.setViewportMprCrosshairSyncCommandById,
    setCrossStudyCalibrationByPairKey: state.setCrossStudyCalibrationByPairKey,
    setManualSequenceSyncRequest: state.setManualSequenceSyncRequest,
    setAnnotationListOpen: state.setAnnotationListOpen,
    setKeyImageListOpen: state.setKeyImageListOpen,
    setDicomTagDialogViewportId: state.setDicomTagDialogViewportId,
    setSettingsOpen: state.setSettingsOpen,
    resetViewerSession: state.resetViewerSession,
  }),
};
